---
- name: Upload NGINX upstream config file
  ansible.builtin.template:
    src: "{{ upstream_template_file }}"
    dest: "{{ upstream_conf_file_location | default('/etc/nginx/conf.d') }}/{{ upstream_conf_file_name | default('upstream.conf') }}"
    backup: yes
    owner: nginx
    group: root
    mode: 0644
  when: nginx_config_upstream_upload_enable | bool
  loop: "{{ upstreams }}"
  tags: nginx_upstream_config_upload